# Load Data
```{r}
library(janitor)
library(sf)
library(here)
library(readr)
library(dplyr)

# 导入全球性别不平等数据
All_tables <- read_csv("D:/UCL/CASA/CASA0005 GIS/wk4/hw4_Data/HDR21-22_Composite_indices_complete_time_series.csv")

GlobalGenderInequalityData <- All_tables [,c("country","gii_2010","gii_2019")] %>%
  na.omit()
  
GlobalGenderInequalityData <- GlobalGenderInequalityData %>%
  mutate(diff = gii_2010 - gii_2019)

diff_GGI <- GlobalGenderInequalityData [,c("country","diff")]
```
```{r}
# 导入全球城市数据
world_cities <- sf::st_read("D:/UCL/CASA/CASA0005 GIS/wk4/hw4_Data/World_Countries_Generalized/World_Countries_Generalized.shp")%>%
  clean_names()
```
```{r}
# 将全球性别不平等数据加入城市数据
cities_GGI <- left_join(world_cities,diff_GGI,by="country") %>%
  na.omit()
```
# plot
```{r}
library(tmap)
tmap_mode('plot')
tm_shape(cities_GGI)+
  tm_polygons('diff',
              style='quantile',n=4,
              palette='YlOrRd',
              title='Gender inequality')+
  tm_layout(title='Gender inequality between 2010 and 2019',
            legend.position = c("left", "bottom"))
```


